package com.adtec.ncps.busi.chnl.bean;

public class Jrnl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.PLAT_DATE
     *
     * @mbggenerated
     */
    private String PLAT_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.SEQ_NO
     *
     * @mbggenerated
     */
    private Integer SEQ_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BRCH_NO
     *
     * @mbggenerated
     */
    private String BRCH_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TELLER_NO
     *
     * @mbggenerated
     */
    private String TELLER_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TERM_NO
     *
     * @mbggenerated
     */
    private String TERM_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CHN_NO
     *
     * @mbggenerated
     */
    private String CHN_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.AREA_NO
     *
     * @mbggenerated
     */
    private String AREA_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ENTR_NO
     *
     * @mbggenerated
     */
    private String ENTR_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BUSI_NO
     *
     * @mbggenerated
     */
    private String BUSI_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ESWT_SEQ
     *
     * @mbggenerated
     */
    private String ESWT_SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_CODE
     *
     * @mbggenerated
     */
    private String TX_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_TYPE
     *
     * @mbggenerated
     */
    private String TX_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_DATE
     *
     * @mbggenerated
     */
    private String TX_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_TIME
     *
     * @mbggenerated
     */
    private String TX_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_SEQ
     *
     * @mbggenerated
     */
    private String TX_SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_DATE
     *
     * @mbggenerated
     */
    private String ACT_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_TIME
     *
     * @mbggenerated
     */
    private String ACT_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_SEQ
     *
     * @mbggenerated
     */
    private String ACT_SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.OTH_DATE
     *
     * @mbggenerated
     */
    private String OTH_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.OTH_TIME
     *
     * @mbggenerated
     */
    private String OTH_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.OTH_SEQ
     *
     * @mbggenerated
     */
    private String OTH_SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RET_CODE
     *
     * @mbggenerated
     */
    private String RET_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RET_MSG
     *
     * @mbggenerated
     */
    private String RET_MSG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.DC_FLAG
     *
     * @mbggenerated
     */
    private String DC_FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.TX_AMT
     *
     * @mbggenerated
     */
    private Double TX_AMT = 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.REC_FEE
     *
     * @mbggenerated
     */
    private Double REC_FEE= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CUST_NO
     *
     * @mbggenerated
     */
    private String CUST_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CUST_NAME
     *
     * @mbggenerated
     */
    private String CUST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BRCH_NO1
     *
     * @mbggenerated
     */
    private String BRCH_NO1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BRCH_NAME1
     *
     * @mbggenerated
     */
    private String BRCH_NAME1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_NO1
     *
     * @mbggenerated
     */
    private String ACT_NO1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_NAME1
     *
     * @mbggenerated
     */
    private String ACT_NAME1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_ADDR1
     *
     * @mbggenerated
     */
    private String ACT_ADDR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CURR_NO1
     *
     * @mbggenerated
     */
    private String CURR_NO1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CURR_IDEN1
     *
     * @mbggenerated
     */
    private String CURR_IDEN1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_TYPE1
     *
     * @mbggenerated
     */
    private String ACT_TYPE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_BAL1
     *
     * @mbggenerated
     */
    private Double ACT_BAL1= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BRCH_NO2
     *
     * @mbggenerated
     */
    private String BRCH_NO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.BRCH_NAME2
     *
     * @mbggenerated
     */
    private String BRCH_NAME2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_NO2
     *
     * @mbggenerated
     */
    private String ACT_NO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_NAME2
     *
     * @mbggenerated
     */
    private String ACT_NAME2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_ADDR2
     *
     * @mbggenerated
     */
    private String ACT_ADDR2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CURR_NO2
     *
     * @mbggenerated
     */
    private String CURR_NO2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.CURR_IDEN2
     *
     * @mbggenerated
     */
    private String CURR_IDEN2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_TYPE2
     *
     * @mbggenerated
     */
    private String ACT_TYPE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.ACT_BAL2
     *
     * @mbggenerated
     */
    private Double ACT_BAL2= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.SUMMARY
     *
     * @mbggenerated
     */
    private String SUMMARY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RMARK1
     *
     * @mbggenerated
     */
    private String RMARK1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RMARK2
     *
     * @mbggenerated
     */
    private String RMARK2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RMARK3
     *
     * @mbggenerated
     */
    private String RMARK3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.RMARK4
     *
     * @mbggenerated
     */
    private String RMARK4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.AMT1
     *
     * @mbggenerated
     */
    private Double AMT1= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.AMT2
     *
     * @mbggenerated
     */
    private Double AMT2= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.AMT3
     *
     * @mbggenerated
     */
    private Double AMT3= 0.00;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_JRNL.AMT4
     *
     * @mbggenerated
     */
    private Double AMT4= 0.00;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.PLAT_DATE
     *
     * @return the value of T_JRNL.PLAT_DATE
     *
     * @mbggenerated
     */
    public String getPLAT_DATE() {
        return PLAT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.PLAT_DATE
     *
     * @param PLAT_DATE the value for T_JRNL.PLAT_DATE
     *
     * @mbggenerated
     */
    public void setPLAT_DATE(String PLAT_DATE) {
        this.PLAT_DATE = PLAT_DATE == null ? null : PLAT_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.SEQ_NO
     *
     * @return the value of T_JRNL.SEQ_NO
     *
     * @mbggenerated
     */
    public Integer getSEQ_NO() {
        return SEQ_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.SEQ_NO
     *
     * @param SEQ_NO the value for T_JRNL.SEQ_NO
     *
     * @mbggenerated
     */
    public void setSEQ_NO(Integer SEQ_NO) {
        this.SEQ_NO = SEQ_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BRCH_NO
     *
     * @return the value of T_JRNL.BRCH_NO
     *
     * @mbggenerated
     */
    public String getBRCH_NO() {
        return BRCH_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BRCH_NO
     *
     * @param BRCH_NO the value for T_JRNL.BRCH_NO
     *
     * @mbggenerated
     */
    public void setBRCH_NO(String BRCH_NO) {
        this.BRCH_NO = BRCH_NO == null ? null : BRCH_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TELLER_NO
     *
     * @return the value of T_JRNL.TELLER_NO
     *
     * @mbggenerated
     */
    public String getTELLER_NO() {
        return TELLER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TELLER_NO
     *
     * @param TELLER_NO the value for T_JRNL.TELLER_NO
     *
     * @mbggenerated
     */
    public void setTELLER_NO(String TELLER_NO) {
        this.TELLER_NO = TELLER_NO == null ? null : TELLER_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TERM_NO
     *
     * @return the value of T_JRNL.TERM_NO
     *
     * @mbggenerated
     */
    public String getTERM_NO() {
        return TERM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TERM_NO
     *
     * @param TERM_NO the value for T_JRNL.TERM_NO
     *
     * @mbggenerated
     */
    public void setTERM_NO(String TERM_NO) {
        this.TERM_NO = TERM_NO == null ? null : TERM_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CHN_NO
     *
     * @return the value of T_JRNL.CHN_NO
     *
     * @mbggenerated
     */
    public String getCHN_NO() {
        return CHN_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CHN_NO
     *
     * @param CHN_NO the value for T_JRNL.CHN_NO
     *
     * @mbggenerated
     */
    public void setCHN_NO(String CHN_NO) {
        this.CHN_NO = CHN_NO == null ? null : CHN_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.AREA_NO
     *
     * @return the value of T_JRNL.AREA_NO
     *
     * @mbggenerated
     */
    public String getAREA_NO() {
        return AREA_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.AREA_NO
     *
     * @param AREA_NO the value for T_JRNL.AREA_NO
     *
     * @mbggenerated
     */
    public void setAREA_NO(String AREA_NO) {
        this.AREA_NO = AREA_NO == null ? null : AREA_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ENTR_NO
     *
     * @return the value of T_JRNL.ENTR_NO
     *
     * @mbggenerated
     */
    public String getENTR_NO() {
        return ENTR_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ENTR_NO
     *
     * @param ENTR_NO the value for T_JRNL.ENTR_NO
     *
     * @mbggenerated
     */
    public void setENTR_NO(String ENTR_NO) {
        this.ENTR_NO = ENTR_NO == null ? null : ENTR_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BUSI_NO
     *
     * @return the value of T_JRNL.BUSI_NO
     *
     * @mbggenerated
     */
    public String getBUSI_NO() {
        return BUSI_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BUSI_NO
     *
     * @param BUSI_NO the value for T_JRNL.BUSI_NO
     *
     * @mbggenerated
     */
    public void setBUSI_NO(String BUSI_NO) {
        this.BUSI_NO = BUSI_NO == null ? null : BUSI_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ESWT_SEQ
     *
     * @return the value of T_JRNL.ESWT_SEQ
     *
     * @mbggenerated
     */
    public String getESWT_SEQ() {
        return ESWT_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ESWT_SEQ
     *
     * @param ESWT_SEQ the value for T_JRNL.ESWT_SEQ
     *
     * @mbggenerated
     */
    public void setESWT_SEQ(String ESWT_SEQ) {
        this.ESWT_SEQ = ESWT_SEQ == null ? null : ESWT_SEQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_CODE
     *
     * @return the value of T_JRNL.TX_CODE
     *
     * @mbggenerated
     */
    public String getTX_CODE() {
        return TX_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_CODE
     *
     * @param TX_CODE the value for T_JRNL.TX_CODE
     *
     * @mbggenerated
     */
    public void setTX_CODE(String TX_CODE) {
        this.TX_CODE = TX_CODE == null ? null : TX_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_TYPE
     *
     * @return the value of T_JRNL.TX_TYPE
     *
     * @mbggenerated
     */
    public String getTX_TYPE() {
        return TX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_TYPE
     *
     * @param TX_TYPE the value for T_JRNL.TX_TYPE
     *
     * @mbggenerated
     */
    public void setTX_TYPE(String TX_TYPE) {
        this.TX_TYPE = TX_TYPE == null ? null : TX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_DATE
     *
     * @return the value of T_JRNL.TX_DATE
     *
     * @mbggenerated
     */
    public String getTX_DATE() {
        return TX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_DATE
     *
     * @param TX_DATE the value for T_JRNL.TX_DATE
     *
     * @mbggenerated
     */
    public void setTX_DATE(String TX_DATE) {
        this.TX_DATE = TX_DATE == null ? null : TX_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_TIME
     *
     * @return the value of T_JRNL.TX_TIME
     *
     * @mbggenerated
     */
    public String getTX_TIME() {
        return TX_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_TIME
     *
     * @param TX_TIME the value for T_JRNL.TX_TIME
     *
     * @mbggenerated
     */
    public void setTX_TIME(String TX_TIME) {
        this.TX_TIME = TX_TIME == null ? null : TX_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_SEQ
     *
     * @return the value of T_JRNL.TX_SEQ
     *
     * @mbggenerated
     */
    public String getTX_SEQ() {
        return TX_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_SEQ
     *
     * @param TX_SEQ the value for T_JRNL.TX_SEQ
     *
     * @mbggenerated
     */
    public void setTX_SEQ(String TX_SEQ) {
        this.TX_SEQ = TX_SEQ == null ? null : TX_SEQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_DATE
     *
     * @return the value of T_JRNL.ACT_DATE
     *
     * @mbggenerated
     */
    public String getACT_DATE() {
        return ACT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_DATE
     *
     * @param ACT_DATE the value for T_JRNL.ACT_DATE
     *
     * @mbggenerated
     */
    public void setACT_DATE(String ACT_DATE) {
        this.ACT_DATE = ACT_DATE == null ? null : ACT_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_TIME
     *
     * @return the value of T_JRNL.ACT_TIME
     *
     * @mbggenerated
     */
    public String getACT_TIME() {
        return ACT_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_TIME
     *
     * @param ACT_TIME the value for T_JRNL.ACT_TIME
     *
     * @mbggenerated
     */
    public void setACT_TIME(String ACT_TIME) {
        this.ACT_TIME = ACT_TIME == null ? null : ACT_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_SEQ
     *
     * @return the value of T_JRNL.ACT_SEQ
     *
     * @mbggenerated
     */
    public String getACT_SEQ() {
        return ACT_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_SEQ
     *
     * @param ACT_SEQ the value for T_JRNL.ACT_SEQ
     *
     * @mbggenerated
     */
    public void setACT_SEQ(String ACT_SEQ) {
        this.ACT_SEQ = ACT_SEQ == null ? null : ACT_SEQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.OTH_DATE
     *
     * @return the value of T_JRNL.OTH_DATE
     *
     * @mbggenerated
     */
    public String getOTH_DATE() {
        return OTH_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.OTH_DATE
     *
     * @param OTH_DATE the value for T_JRNL.OTH_DATE
     *
     * @mbggenerated
     */
    public void setOTH_DATE(String OTH_DATE) {
        this.OTH_DATE = OTH_DATE == null ? null : OTH_DATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.OTH_TIME
     *
     * @return the value of T_JRNL.OTH_TIME
     *
     * @mbggenerated
     */
    public String getOTH_TIME() {
        return OTH_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.OTH_TIME
     *
     * @param OTH_TIME the value for T_JRNL.OTH_TIME
     *
     * @mbggenerated
     */
    public void setOTH_TIME(String OTH_TIME) {
        this.OTH_TIME = OTH_TIME == null ? null : OTH_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.OTH_SEQ
     *
     * @return the value of T_JRNL.OTH_SEQ
     *
     * @mbggenerated
     */
    public String getOTH_SEQ() {
        return OTH_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.OTH_SEQ
     *
     * @param OTH_SEQ the value for T_JRNL.OTH_SEQ
     *
     * @mbggenerated
     */
    public void setOTH_SEQ(String OTH_SEQ) {
        this.OTH_SEQ = OTH_SEQ == null ? null : OTH_SEQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RET_CODE
     *
     * @return the value of T_JRNL.RET_CODE
     *
     * @mbggenerated
     */
    public String getRET_CODE() {
        return RET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RET_CODE
     *
     * @param RET_CODE the value for T_JRNL.RET_CODE
     *
     * @mbggenerated
     */
    public void setRET_CODE(String RET_CODE) {
        this.RET_CODE = RET_CODE == null ? null : RET_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RET_MSG
     *
     * @return the value of T_JRNL.RET_MSG
     *
     * @mbggenerated
     */
    public String getRET_MSG() {
        return RET_MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RET_MSG
     *
     * @param RET_MSG the value for T_JRNL.RET_MSG
     *
     * @mbggenerated
     */
    public void setRET_MSG(String RET_MSG) {
        this.RET_MSG = RET_MSG == null ? null : RET_MSG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.DC_FLAG
     *
     * @return the value of T_JRNL.DC_FLAG
     *
     * @mbggenerated
     */
    public String getDC_FLAG() {
        return DC_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.DC_FLAG
     *
     * @param DC_FLAG the value for T_JRNL.DC_FLAG
     *
     * @mbggenerated
     */
    public void setDC_FLAG(String DC_FLAG) {
        this.DC_FLAG = DC_FLAG == null ? null : DC_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.TX_AMT
     *
     * @return the value of T_JRNL.TX_AMT
     *
     * @mbggenerated
     */
    public Double getTX_AMT() {
        return TX_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.TX_AMT
     *
     * @param TX_AMT the value for T_JRNL.TX_AMT
     *
     * @mbggenerated
     */
    public void setTX_AMT(Double TX_AMT) {
        this.TX_AMT = TX_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.REC_FEE
     *
     * @return the value of T_JRNL.REC_FEE
     *
     * @mbggenerated
     */
    public Double getREC_FEE() {
        return REC_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.REC_FEE
     *
     * @param REC_FEE the value for T_JRNL.REC_FEE
     *
     * @mbggenerated
     */
    public void setREC_FEE(Double REC_FEE) {
        this.REC_FEE = REC_FEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CUST_NO
     *
     * @return the value of T_JRNL.CUST_NO
     *
     * @mbggenerated
     */
    public String getCUST_NO() {
        return CUST_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CUST_NO
     *
     * @param CUST_NO the value for T_JRNL.CUST_NO
     *
     * @mbggenerated
     */
    public void setCUST_NO(String CUST_NO) {
        this.CUST_NO = CUST_NO == null ? null : CUST_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CUST_NAME
     *
     * @return the value of T_JRNL.CUST_NAME
     *
     * @mbggenerated
     */
    public String getCUST_NAME() {
        return CUST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CUST_NAME
     *
     * @param CUST_NAME the value for T_JRNL.CUST_NAME
     *
     * @mbggenerated
     */
    public void setCUST_NAME(String CUST_NAME) {
        this.CUST_NAME = CUST_NAME == null ? null : CUST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BRCH_NO1
     *
     * @return the value of T_JRNL.BRCH_NO1
     *
     * @mbggenerated
     */
    public String getBRCH_NO1() {
        return BRCH_NO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BRCH_NO1
     *
     * @param BRCH_NO1 the value for T_JRNL.BRCH_NO1
     *
     * @mbggenerated
     */
    public void setBRCH_NO1(String BRCH_NO1) {
        this.BRCH_NO1 = BRCH_NO1 == null ? null : BRCH_NO1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BRCH_NAME1
     *
     * @return the value of T_JRNL.BRCH_NAME1
     *
     * @mbggenerated
     */
    public String getBRCH_NAME1() {
        return BRCH_NAME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BRCH_NAME1
     *
     * @param BRCH_NAME1 the value for T_JRNL.BRCH_NAME1
     *
     * @mbggenerated
     */
    public void setBRCH_NAME1(String BRCH_NAME1) {
        this.BRCH_NAME1 = BRCH_NAME1 == null ? null : BRCH_NAME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_NO1
     *
     * @return the value of T_JRNL.ACT_NO1
     *
     * @mbggenerated
     */
    public String getACT_NO1() {
        return ACT_NO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_NO1
     *
     * @param ACT_NO1 the value for T_JRNL.ACT_NO1
     *
     * @mbggenerated
     */
    public void setACT_NO1(String ACT_NO1) {
        this.ACT_NO1 = ACT_NO1 == null ? null : ACT_NO1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_NAME1
     *
     * @return the value of T_JRNL.ACT_NAME1
     *
     * @mbggenerated
     */
    public String getACT_NAME1() {
        return ACT_NAME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_NAME1
     *
     * @param ACT_NAME1 the value for T_JRNL.ACT_NAME1
     *
     * @mbggenerated
     */
    public void setACT_NAME1(String ACT_NAME1) {
        this.ACT_NAME1 = ACT_NAME1 == null ? null : ACT_NAME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_ADDR1
     *
     * @return the value of T_JRNL.ACT_ADDR1
     *
     * @mbggenerated
     */
    public String getACT_ADDR1() {
        return ACT_ADDR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_ADDR1
     *
     * @param ACT_ADDR1 the value for T_JRNL.ACT_ADDR1
     *
     * @mbggenerated
     */
    public void setACT_ADDR1(String ACT_ADDR1) {
        this.ACT_ADDR1 = ACT_ADDR1 == null ? null : ACT_ADDR1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CURR_NO1
     *
     * @return the value of T_JRNL.CURR_NO1
     *
     * @mbggenerated
     */
    public String getCURR_NO1() {
        return CURR_NO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CURR_NO1
     *
     * @param CURR_NO1 the value for T_JRNL.CURR_NO1
     *
     * @mbggenerated
     */
    public void setCURR_NO1(String CURR_NO1) {
        this.CURR_NO1 = CURR_NO1 == null ? null : CURR_NO1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CURR_IDEN1
     *
     * @return the value of T_JRNL.CURR_IDEN1
     *
     * @mbggenerated
     */
    public String getCURR_IDEN1() {
        return CURR_IDEN1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CURR_IDEN1
     *
     * @param CURR_IDEN1 the value for T_JRNL.CURR_IDEN1
     *
     * @mbggenerated
     */
    public void setCURR_IDEN1(String CURR_IDEN1) {
        this.CURR_IDEN1 = CURR_IDEN1 == null ? null : CURR_IDEN1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_TYPE1
     *
     * @return the value of T_JRNL.ACT_TYPE1
     *
     * @mbggenerated
     */
    public String getACT_TYPE1() {
        return ACT_TYPE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_TYPE1
     *
     * @param ACT_TYPE1 the value for T_JRNL.ACT_TYPE1
     *
     * @mbggenerated
     */
    public void setACT_TYPE1(String ACT_TYPE1) {
        this.ACT_TYPE1 = ACT_TYPE1 == null ? null : ACT_TYPE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_BAL1
     *
     * @return the value of T_JRNL.ACT_BAL1
     *
     * @mbggenerated
     */
    public Double getACT_BAL1() {
        return ACT_BAL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_BAL1
     *
     * @param ACT_BAL1 the value for T_JRNL.ACT_BAL1
     *
     * @mbggenerated
     */
    public void setACT_BAL1(Double ACT_BAL1) {
        this.ACT_BAL1 = ACT_BAL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BRCH_NO2
     *
     * @return the value of T_JRNL.BRCH_NO2
     *
     * @mbggenerated
     */
    public String getBRCH_NO2() {
        return BRCH_NO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BRCH_NO2
     *
     * @param BRCH_NO2 the value for T_JRNL.BRCH_NO2
     *
     * @mbggenerated
     */
    public void setBRCH_NO2(String BRCH_NO2) {
        this.BRCH_NO2 = BRCH_NO2 == null ? null : BRCH_NO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.BRCH_NAME2
     *
     * @return the value of T_JRNL.BRCH_NAME2
     *
     * @mbggenerated
     */
    public String getBRCH_NAME2() {
        return BRCH_NAME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.BRCH_NAME2
     *
     * @param BRCH_NAME2 the value for T_JRNL.BRCH_NAME2
     *
     * @mbggenerated
     */
    public void setBRCH_NAME2(String BRCH_NAME2) {
        this.BRCH_NAME2 = BRCH_NAME2 == null ? null : BRCH_NAME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_NO2
     *
     * @return the value of T_JRNL.ACT_NO2
     *
     * @mbggenerated
     */
    public String getACT_NO2() {
        return ACT_NO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_NO2
     *
     * @param ACT_NO2 the value for T_JRNL.ACT_NO2
     *
     * @mbggenerated
     */
    public void setACT_NO2(String ACT_NO2) {
        this.ACT_NO2 = ACT_NO2 == null ? null : ACT_NO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_NAME2
     *
     * @return the value of T_JRNL.ACT_NAME2
     *
     * @mbggenerated
     */
    public String getACT_NAME2() {
        return ACT_NAME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_NAME2
     *
     * @param ACT_NAME2 the value for T_JRNL.ACT_NAME2
     *
     * @mbggenerated
     */
    public void setACT_NAME2(String ACT_NAME2) {
        this.ACT_NAME2 = ACT_NAME2 == null ? null : ACT_NAME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_ADDR2
     *
     * @return the value of T_JRNL.ACT_ADDR2
     *
     * @mbggenerated
     */
    public String getACT_ADDR2() {
        return ACT_ADDR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_ADDR2
     *
     * @param ACT_ADDR2 the value for T_JRNL.ACT_ADDR2
     *
     * @mbggenerated
     */
    public void setACT_ADDR2(String ACT_ADDR2) {
        this.ACT_ADDR2 = ACT_ADDR2 == null ? null : ACT_ADDR2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CURR_NO2
     *
     * @return the value of T_JRNL.CURR_NO2
     *
     * @mbggenerated
     */
    public String getCURR_NO2() {
        return CURR_NO2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CURR_NO2
     *
     * @param CURR_NO2 the value for T_JRNL.CURR_NO2
     *
     * @mbggenerated
     */
    public void setCURR_NO2(String CURR_NO2) {
        this.CURR_NO2 = CURR_NO2 == null ? null : CURR_NO2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.CURR_IDEN2
     *
     * @return the value of T_JRNL.CURR_IDEN2
     *
     * @mbggenerated
     */
    public String getCURR_IDEN2() {
        return CURR_IDEN2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.CURR_IDEN2
     *
     * @param CURR_IDEN2 the value for T_JRNL.CURR_IDEN2
     *
     * @mbggenerated
     */
    public void setCURR_IDEN2(String CURR_IDEN2) {
        this.CURR_IDEN2 = CURR_IDEN2 == null ? null : CURR_IDEN2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_TYPE2
     *
     * @return the value of T_JRNL.ACT_TYPE2
     *
     * @mbggenerated
     */
    public String getACT_TYPE2() {
        return ACT_TYPE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_TYPE2
     *
     * @param ACT_TYPE2 the value for T_JRNL.ACT_TYPE2
     *
     * @mbggenerated
     */
    public void setACT_TYPE2(String ACT_TYPE2) {
        this.ACT_TYPE2 = ACT_TYPE2 == null ? null : ACT_TYPE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.ACT_BAL2
     *
     * @return the value of T_JRNL.ACT_BAL2
     *
     * @mbggenerated
     */
    public Double getACT_BAL2() {
        return ACT_BAL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.ACT_BAL2
     *
     * @param ACT_BAL2 the value for T_JRNL.ACT_BAL2
     *
     * @mbggenerated
     */
    public void setACT_BAL2(Double ACT_BAL2) {
        this.ACT_BAL2 = ACT_BAL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.SUMMARY
     *
     * @return the value of T_JRNL.SUMMARY
     *
     * @mbggenerated
     */
    public String getSUMMARY() {
        return SUMMARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.SUMMARY
     *
     * @param SUMMARY the value for T_JRNL.SUMMARY
     *
     * @mbggenerated
     */
    public void setSUMMARY(String SUMMARY) {
        this.SUMMARY = SUMMARY == null ? null : SUMMARY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RMARK1
     *
     * @return the value of T_JRNL.RMARK1
     *
     * @mbggenerated
     */
    public String getRMARK1() {
        return RMARK1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RMARK1
     *
     * @param RMARK1 the value for T_JRNL.RMARK1
     *
     * @mbggenerated
     */
    public void setRMARK1(String RMARK1) {
        this.RMARK1 = RMARK1 == null ? null : RMARK1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RMARK2
     *
     * @return the value of T_JRNL.RMARK2
     *
     * @mbggenerated
     */
    public String getRMARK2() {
        return RMARK2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RMARK2
     *
     * @param RMARK2 the value for T_JRNL.RMARK2
     *
     * @mbggenerated
     */
    public void setRMARK2(String RMARK2) {
        this.RMARK2 = RMARK2 == null ? null : RMARK2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RMARK3
     *
     * @return the value of T_JRNL.RMARK3
     *
     * @mbggenerated
     */
    public String getRMARK3() {
        return RMARK3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RMARK3
     *
     * @param RMARK3 the value for T_JRNL.RMARK3
     *
     * @mbggenerated
     */
    public void setRMARK3(String RMARK3) {
        this.RMARK3 = RMARK3 == null ? null : RMARK3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.RMARK4
     *
     * @return the value of T_JRNL.RMARK4
     *
     * @mbggenerated
     */
    public String getRMARK4() {
        return RMARK4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.RMARK4
     *
     * @param RMARK4 the value for T_JRNL.RMARK4
     *
     * @mbggenerated
     */
    public void setRMARK4(String RMARK4) {
        this.RMARK4 = RMARK4 == null ? null : RMARK4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.AMT1
     *
     * @return the value of T_JRNL.AMT1
     *
     * @mbggenerated
     */
    public Double getAMT1() {
        return AMT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.AMT1
     *
     * @param AMT1 the value for T_JRNL.AMT1
     *
     * @mbggenerated
     */
    public void setAMT1(Double AMT1) {
        this.AMT1 = AMT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.AMT2
     *
     * @return the value of T_JRNL.AMT2
     *
     * @mbggenerated
     */
    public Double getAMT2() {
        return AMT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.AMT2
     *
     * @param AMT2 the value for T_JRNL.AMT2
     *
     * @mbggenerated
     */
    public void setAMT2(Double AMT2) {
        this.AMT2 = AMT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.AMT3
     *
     * @return the value of T_JRNL.AMT3
     *
     * @mbggenerated
     */
    public Double getAMT3() {
        return AMT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.AMT3
     *
     * @param AMT3 the value for T_JRNL.AMT3
     *
     * @mbggenerated
     */
    public void setAMT3(Double AMT3) {
        this.AMT3 = AMT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_JRNL.AMT4
     *
     * @return the value of T_JRNL.AMT4
     *
     * @mbggenerated
     */
    public Double getAMT4() {
        return AMT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_JRNL.AMT4
     *
     * @param AMT4 the value for T_JRNL.AMT4
     *
     * @mbggenerated
     */
    public void setAMT4(Double AMT4) {
        this.AMT4 = AMT4;
    }
}